/* The "How to fill" sheet written into every generated workbook. */
export const HOW_TO_LINES = [
  "HOW TO FILL THIS WORKBOOK (on site)",
  "",
  "Yellow cells are the ones to fill in. Everything else is fixed.",
  "One row per item, top of the network first. The drawing's topology",
  "comes only from ID and Feeds From: an item is drawn under whatever it",
  "feeds from. Row order sets left-to-right order. A half-filled row still",
  "draws, with an open terminal where the supply or the load is missing.",
  "",
  "COLUMNS",
  "  ID          a short unique tag you invent: MV1, RMU1, TX1, BB1, F1",
  "  Type        pick from the dropdown (see TYPES)",
  "  Description free text, printed as a label (a few words also change",
  "              the symbol - see WORDS)",
  "  Rating      from the nameplate: 1000 kVA, 630 A, 315 kW",
  "  Voltage     from the nameplate: 11/0.4 kV, 400 V - printed only",
  "  Protection  the device on THIS item's supply side: CB, LBS, Fuse,",
  "              Fuse-switch, Contactor, Fuse-contactor; blank = the usual",
  "              default; two supplies: a comma list in Feeds From order",
  "              (LBS, CB). Free text on a busbar (87B differential) is",
  "              printed as a zone label.",
  "  Feeds From  the ID of the item supplying this one; comma for two",
  "              supplies (BB1, BB2 - MV1, MV2)",
  "  Notes       anything worth remembering; printed on ties; a few",
  "              leading words change the symbol - see WORDS",
  "",
  "TYPES (and how each one draws)",
  "  MV Incomer     source tick at the top; feeds an MV Busbar, RMU or TX",
  "  MV Busbar      thick bar, a breaker on every way; a board fed from",
  "                 another board sits one tier lower",
  "  RMU            dashed enclosure, load-break switches on the ways in,",
  "                 fuse-switches on the tee-offs; RMUs that feed from",
  "                 each other form a ring side by side",
  "  Transformer    two circles; step-down or step-up follows Feeds From;",
  "                 off an LV board feeding only Pumps (or nothing",
  "                 yet) it hangs under the board as one of its ways",
  "  Generator      G circle over the board it feeds, on top of a step-up",
  "                 column, or under a reversed one",
  "  Pump           M 3~ circle: transformer row on MV gear, feeder band",
  "                 on an LV board or an MCC, under a transformer of its own",
  "  LV Busbar      thick bar with its feeders; fed from a Feeder or",
  "                 another LV Busbar it is a sub-board on the row below",
  "  Feeder         the way out of a board: a drop, the device its own",
  "                 Protection names (none when the cell is empty) and an",
  "                 arrow. Anything may feed from a Feeder — a Pump, an",
  "                 MCC, a Transformer, a sub-board — and then it hangs",
  "                 there and the arrow goes. Leave Protection empty and",
  "                 the equipment's own device is the only one on the run;",
  "                 write one and it is drawn above the equipment's.",
  "                 On MV gear a Feeder is an outgoing cable",
  "  MCC            labelled box; with Pumps/Feeders under it, a bus of",
  "                 its own on the row below with the motor ways off it,",
  "                 incomer, box and bus inside a dashed outline; on a",
  "                 transformer with no board it is that board; on a",
  "                 transformer that feeds a board, a way of the board",
  "  Bus Coupler    breaker between two busbars of the same kind; between",
  "                 a board and a Generator, a changeover (ATS)",
  "  Capacitor Bank plates to earth (LV board or MV gear); needs no load",
  "  Earthing/NER   resistor box to earth; needs no load",
  "  Surge Arrester arrester box to earth; needs no load",
  "",
  "WIRING RECIPES (Feeds From)",
  "  Step-down: TX feeds from the MV board/RMU; the LV Busbar from TX.",
  "  Step-up from a genset or PV board: TX feeds from the Generator (or",
  "    generation LV Busbar); the MV Busbar/RMU feeds from TX.",
  "  Step-up from a live LV board: TX feeds from that board; the MV",
  "    gear feeds from TX.",
  "  Genset straight onto a board: the board feeds from MV, DG1, DG2;",
  "    the Generator rows have Feeds From blank.",
  "  Standby set on a changeover: a Bus Coupler row ATS feeding from",
  "    MSB3, G1.",
  "  Sub-board (DB): the LV Busbar feeds from the Feeder that supplies",
  "    it, or straight from the main LV Busbar.",
  "  Motors in an MCC: the MCC feeds from the board; each Pump from the MCC.",
  "  Equipment on a way: write the Feeder first (Protection blank), then",
  "    the Pump/MCC/Transformer feeding from it. One device on the run.",
  "  Bus tie: a Bus Coupler feeding from BB1, BB2; Notes Normally open.",
  "  Board with two supplies: the board feeds from TX1, TX2.",
  "  Ring of RMUs from a board: each RMU feeds from its neighbours",
  "    (PB, R2 ... R4, PB); a link written on both rows is drawn once.",
  "  Open point of a ring: Notes on one RMU: N.O. towards RMU2.",
  "  Spur or sub-ring off an RMU: the spur RMU feeds from the ring RMU;",
  "    a sub-ring's two RMUs feed from it and from each other.",
  "  Several voltage levels: the lower board feeds from the transformer,",
  "    the transformer from the upper board; tiers follow the wiring,",
  "    never the Voltage column.",
  "  Outgoing MV cable, capacitor bank, NER: a Feeder, Capacitor Bank",
  "    or Earthing/NER row feeding from the MV board or RMU.",
  "",
  "WORDS THAT CHANGE THE SYMBOL (read from Description and Notes)",
  "  VSD / VFD / drive        on a Pump: a drive box on the motor's drop",
  "  Spare / Future /         at the start of Notes: the way drawn dashed",
  "    Out of service",
  "  N.O. / Normally open     on a Bus Coupler: printed under it",
  "  N.O. towards RMU2,       on an RMU: an N.O. marker on the cable to",
  "    ring open here           the RMU named, or under the box",
  "  capacitor / PFC / kvar   on a Feeder: drawn as a capacitor bank",
  "  NER / earthing / zig-zag on a Feeder, or a Transformer with nothing",
  "                           on its output: earthing resistor / tx",
  "  arrester / surge         on a Feeder: drawn as a surge arrester",
  "  Protection words: CB MCCB MCB ACB - LBS isolator - Fuse -",
  "    Fuse-switch SFU - Contactor - Fuse-contactor starter",
  "",
  "BACK AT THE OFFICE",
  "  Open sld_sketchpad.html and use Import to load this workbook: the",
  "  drawing rebuilds live; Download PDF / SVG / DXF export it.",
  "  node src/cli/sld.js draw thisfile.xlsx       -> the SVG",
  "  node src/cli/sld.js pdf  thisfile.xlsx       -> one A3 page with the",
  "                                                  equipment table",
  "  node src/cli/sld.js dxf  thisfile.xlsx       -> the DXF, same",
];
